# Generated by Django 3.0.7 on 2020-07-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20200704_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
    ]
