# Generated by Django 3.0.7 on 2020-07-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_auto_20200705_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
