# Generated by Django 3.0.7 on 2020-07-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0014_comment_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='users',
            new_name='profile',
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
