# Generated by Django 3.0.7 on 2020-07-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_auto_20200705_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
    ]
