# Generated by Django 3.0.7 on 2020-07-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0016_remove_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='image',
        ),
    ]
