# Generated by Django 3.0.7 on 2020-07-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0018_auto_20200706_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='profile',
            new_name='users',
        ),
    ]
